// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BurnupPoint = { label: string, date: string, doneSp: number, scopeSp: number, idealSp: number, };
