// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BurnupPoint } from "./BurnupPoint";
import type { GanttRow } from "./GanttRow";
import type { Increment } from "./Increment";
import type { Insight } from "./Insight";
import type { Kpis } from "./Kpis";
import type { Sprint } from "./Sprint";
import type { SprintCompletionPoint } from "./SprintCompletionPoint";

export type DashboardData = { increment: Increment, kpis: Kpis, gantt: Array<GanttRow>, burnup: Array<BurnupPoint>, sprintCompletion: Array<SprintCompletionPoint>, insights: Array<Insight>, sprints: Array<Sprint>, lastSynced: string | null, };
