// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusCategory } from "./StatusCategory";

export type Epic = { key: string, name: string, owner: string | null, 
/**
 * The epic's own story-point estimate (used only when it has no children).
 */
sp: number | null, startDate: string | null, endDate: string | null, statusCategory: StatusCategory, 
/**
 * Name of a previous increment this epic was planned for, if any.
 */
carriedFrom: string | null, 
/**
 * Epic no longer matches the increment JQL but is kept visible.
 */
removedFromPlan: boolean, };
