// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epic } from "./Epic";
import type { Issue } from "./Issue";
import type { ProgressBreakdown } from "./ProgressBreakdown";
import type { Sprint } from "./Sprint";

export type EpicDetail = { epic: Epic, breakdown: ProgressBreakdown, expectedProgress: number, atRisk: boolean, issues: Array<Issue>, descoped: Array<Issue>, sprints: Array<Sprint>, };
