// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldMapping = { storyPoints: string | null, epicLink: string | null, sprint: string | null, epicStart: string | null, epicEnd: string | null, };
