// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GanttRow = { epicKey: string, name: string, owner: string | null, startDate: string | null, endDate: string | null, progress: number, doneSp: number, inProgressSp: number, totalSp: number, atRisk: boolean, carriedOver: boolean, removedFromPlan: boolean, spillSp: number, unestimatedCount: number, noChildren: boolean, };
