// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Increment = { id: number, name: string, jql: string, startDate: string, endDate: string, isActive: boolean, };
