// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsightSeverity } from "./InsightSeverity";

export type Insight = { id: string, severity: InsightSeverity, title: string, detail: string, spImpact: number, };
