// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One issue's relationship with one sprint — the spillover backbone.
 */
export type IssueSprint = { sprintId: number, 
/**
 * In the sprint at sprint start (or within the first 24h grace window).
 */
wasCommitted: boolean, addedMidSprint: boolean, 
/**
 * Done at sprint close — `None` for sprints that are not closed yet.
 */
doneAtClose: boolean | null, };
