// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Kpis = { progress: number, doneSp: number, totalSp: number, inProgressSp: number, blockedSp: number, expectedProgress: number, 
/**
 * progress − expected_progress (negative = behind plan).
 */
variance: number, carriedForwardSp: number, chronicSpillCount: number, scopeAddedSp: number, scopeRemovedSp: number, descopedSp: number, unestimatedCount: number, imputedRatio: number, };
