// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProgressBreakdown = { totalSp: number, doneSp: number, inProgressSp: number, notStartedSp: number, blockedSp: number, descopedSp: number, 
/**
 * done_sp / total_sp in [0, 1]; 0 when nothing is in scope.
 */
progress: number, totalCount: number, doneCount: number, unestimatedCount: number, imputedSp: number, };
