// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";

export type SaveConnectionInput = { baseUrl: string, username: string, 
/**
 * Omitted = keep the already-stored PAT.
 */
pat: string | null, authMode: AuthMode | null, };
