// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionView } from "./ConnectionView";
import type { FieldMapping } from "./FieldMapping";
import type { Increment } from "./Increment";
import type { SprintNaming } from "./SprintNaming";

export type SettingsView = { connection: ConnectionView | null, fieldMapping: FieldMapping | null, projects: Array<string>, blockedStatuses: Array<string>, epicChildrenClause: string | null, sprintNaming: SprintNaming, increments: Array<Increment>, activeIncrementId: number | null, };
