// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epic } from "./Epic";
import type { SpilledIssueRow } from "./SpilledIssueRow";
import type { SprintCompletionPoint } from "./SprintCompletionPoint";

export type SpilloverReport = { carriedForwardSp: number, 
/**
 * Issues that spilled across ≥ 2 sprints — the chronic offenders.
 */
chronic: Array<SpilledIssueRow>, 
/**
 * Every spilled, still-open issue, worst first.
 */
all: Array<SpilledIssueRow>, 
/**
 * Epics carried over from a previous increment.
 */
carriedEpics: Array<Epic>, perSprint: Array<SprintCompletionPoint>, };
