// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Issue } from "./Issue";
import type { Sprint } from "./Sprint";
import type { SprintCompletionPoint } from "./SprintCompletionPoint";

export type SprintDetail = { sprint: Sprint, stats: SprintCompletionPoint, committed: Array<Issue>, added: Array<Issue>, spilled: Array<Issue>, };
