// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SprintState } from "./SprintState";

export type Sprint = { id: number, name: string, state: SprintState, startDate: string | null, endDate: string | null, boardId: number | null, };
