// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncSummary = { epics: number, issues: number, sprints: number, durationMs: number, };
